historico = [
  {
    'data': '04/05',
    'ausente': 'ALESSANDRA DA SILVA CRUZ',
    'local': 'INSS',
    'reserva': None,
    'motivo': 'INSS / POSTO VAGO',
    'obs': None
  },
 {'data': '04/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'HÉLVIO ESTEVES',
  'reserva': 'CLAUDIMARY REJIANE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'ATESTADO MÉDICO',
  'reserva': None,
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSINÉIA MARTINIANO',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA - BIBLIOTECA',
  'reserva': 'ELAINE POTIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL LONDRINA',
  'reserva': 'ROSÂNGELA BIRAL',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'MOACIR CAMARGO',
  'reserva': 'EDNA APARECIDA',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'AMÉRICA SABINO',
  'reserva': 'DAYANE DOS SANTOS',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'JULIANO STINGHEN',
  'reserva': 'NAIARA CRISTINA',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'IGNÊS CORSO',
  'reserva': 'FRANCIELE CARVALHO',
  'motivo': 'ATESTADO CIRÚRGICO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'NOEMI MALANGA',
  'reserva': 'LAÍS CAVALCANTE',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ CRIMINAL LONDRINA',
  'reserva': 'ABIQUEILA PEREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'VILMA ELISA',
  'reserva': 'LARISSA NATALINA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'TEREZA CANHADA',
  'reserva': 'JÉSSICA TRINDADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'JANAÍNA RIBEIRO DE ASSIS',
  'local': 'FALTOU SEM JUSTIFICATIVA',
  'reserva': 'FALTOU SEM JUSTIFICATIVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'MÉLVIN JONNES',
  'reserva': 'CAROL DANDARA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '04/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'CMEI MARISA ARRUDA',
  'reserva': 'JONATHAS',
  'motivo': 'ATESTADO ATÉ DIA 06.05',
  'obs': None},
 {'data': '04/05',
  'ausente': 'JEFFERSON',
  'local': 'APARECIDO HONORATO',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'APARECIDO HONORATO',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA - MORINGÃO',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '04/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'SECRETARIA - MORINGÃO',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'JOSÉ GASPARINI - ANEXO',
  'reserva': 'SUELI RODRIGUES DE SOUZA',
  'motivo': 'ATESTADO ATÉ DIA 06.05',
  'obs': None},
 {'data': '05/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'ATESTADO',
  'reserva': None,
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSINÉIA MARTINIANO',
  'motivo': 'POSTO VAGO',
  'obs': '90 DIAS'},
 {'data': '05/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA - BIBLIOTECA',
  'reserva': 'ELAINE POTIRA',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'SOLANGE ANDRADE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'ROSÂNGELA BIRAL',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'AMÉRICA SABINO',
  'reserva': 'DAIANE DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'SCHERER',
  'reserva': 'VAGA 44h EM ABERTO',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'MARINA SABÓIA',
  'reserva': 'JULIANA DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'CLEMILDE MARTINS',
  'reserva': 'INGRID SANTOS',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'REGINA CONRADI',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO',
  'reserva': 'FRANCIELE CARVALHO',
  'motivo': 'ATESTADO CIRURGICO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'TERESA CANHADA',
  'reserva': 'JÉSSICA TRINDADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'JANAÍNA RIBEIRO DE ASSIS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'MELVIN JONNES',
  'reserva': 'CAROLINA DANDARA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '05/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'MARISA ARRUDA',
  'reserva': 'PAULO AQUINO',
  'motivo': 'ATESTADO ATÉ DIA 06.05',
  'obs': None},
 {'data': '05/05',
  'ausente': 'JEFFERSON',
  'local': 'EM TRABALHO E SABER',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM TRABALHO E SABER',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA - MORINGÃO',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '05/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'SECRETARIA - MORINGÃO',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'JOSÉ GASPARINI',
  'reserva': 'SUELI RODRIGUES',
  'motivo': 'ATESTADO ATÉ HOJE',
  'obs': None},
 {'data': '06/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'CORVETA',
  'reserva': 'LILIAN FERNANDES',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSINÉIA MARTINIANO',
  'motivo': 'AFASTAMENTO',
  'obs': '90 DIAS'},
 {'data': '06/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA - BIBLIOTECA',
  'reserva': 'ELAINE POTIRA',
  'motivo': 'ATESTADO MÉDICO 15 DIAS',
  'obs': None},
 {'data': '06/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'BEATRIZ DA SILVA CAMPOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'ROSÂNGELA BIRAL',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'JULIANO STINGHEN',
  'reserva': 'ADRIANA SILVA DOS SANTOS',
  'motivo': 'ATESTADO',
  'obs': '2 DIAS'},
 {'data': '06/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'VILMA ELISA',
  'reserva': 'LARISSA NATALINA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'LUIZ MARQUES CASTELO',
  'reserva': 'LUCILENE DE SOUZA',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'CECÍLIA ERMÍNIA',
  'reserva': 'ROSELI REIS',
  'motivo': 'PERÍODO DA TARDE',
  'obs': None},
 {'data': '06/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'ABIQUEILA PEREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNES CORSO',
  'reserva': 'FRANCIELE C. DE OLIVEIRA',
  'motivo': 'ATESTADO MÉDICO',
  'obs': '30 DIAS'},
 {'data': '06/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'TERESA CANHADA',
  'reserva': 'JÉSSICA TRINDADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'HIKOMA UDIHARA',
  'reserva': 'LUANA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'JANAÍNA RIBEIRO DE ASSIS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '06/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'MELVIN JONNES',
  'reserva': 'CAROLINA DANDARA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '06/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'MARISA ARRUDA',
  'reserva': 'JONATHAS',
  'motivo': 'ATESTADO MÉDICO',
  'obs': '3 DIAS'},
 {'data': '07/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'WATER OKANO',
  'reserva': 'ROSÂNGELA GUSMÃO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '07/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'VILMA ELIZA',
  'reserva': 'LARISSA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '07/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSINÉIA MARTINIANO',
  'motivo': 'AFASTAMENTO',
  'obs': '90 DIAS'},
 {'data': '07/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SCHERER',
  'reserva': 'VAGA 44h EM ABERTO',
  'motivo': 'POSTO VAGO',
  'obs': 'NÃO COBRIU'},
 {'data': '07/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'SOLÂNGE DE ANDRADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '07/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'ROSÃNGELA BIRAL',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'BEATRIZ DA SILVA CAMPOS',
  'motivo': 'DEMISSÃO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'AMÉRICA SABINO',
  'reserva': 'GILVANETE COSTA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'CRAS - SUL B',
  'reserva': 'MÁRCIA FRANCISCA SILVA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'MARIA TERESA',
  'reserva': 'ADRIANA CRISTINA SOUZA',
  'motivo': 'MEIO PERÍODO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'CRISTIANE DOS SANTOS',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO',
  'reserva': 'FRANCIELE CARVALHO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '07/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'TERESA CANHADA',
  'reserva': 'JÉSSICA TRINDADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'VALÉRIA VERONESI',
  'reserva': 'LUZIA CAZARIN',
  'motivo': 'ATESTADO MÉDICO',
  'obs': '2 DIAS'},
 {'data': '07/05',
  'ausente': 'JANAÍNA RIBEIRO DE ASSIS',
  'local': 'JUSTA CAUSA',
  'reserva': 'JUSTA CAUSA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'MELVIN JONNES',
  'reserva': 'CAROLINA DANDARA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '07/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'MARIA CÂNDIDO PEIXOTO',
  'reserva': 'JERRI ADRIANI',
  'motivo': 'ATESTADO 15 DIAS',
  'obs': None},
 {'data': '08/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'WATER OKANO',
  'reserva': 'ROSÂNGELA GUSMÃO',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '08/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '08/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSINÉIA MARTINIANO',
  'motivo': 'POSTO VAGO',
  'obs': '90 DIAS'},
 {'data': '08/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'VALÉRIA VERONESI',
  'reserva': 'ROSÂNGELA A. ROCHA',
  'motivo': 'CONSULTA AS 10H',
  'obs': None},
 {'data': '08/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO INDIRETA',
  'reserva': 'RESCISÃO INDIRETA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ LONDRINA',
  'reserva': 'SOLANGE ANDRADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '08/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ LONDRINA',
  'reserva': 'ROSÃNGELA BIRAL',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'TJ LONDRINA',
  'reserva': 'BEATRIZ DA SILVA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'AMÉRICA SABINO',
  'reserva': 'GILVANETE COSTA',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'CRAS-SUL B',
  'reserva': 'MÁRCIA FRANCISCA SILVA',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'MARIA TERESA',
  'reserva': 'MARIA TEREZA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '08/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ LONDRINA',
  'reserva': 'CRISTIANE DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '08/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO',
  'reserva': 'FRANCIELE CARVALHO',
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '08/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'TERESA CANHADA',
  'reserva': 'JÉSSICA TRINDADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'VALÉRIA VERONESI',
  'reserva': 'LUZIA CAZARIN',
  'motivo': 'ATESTADO MÉDICO',
  'obs': '2 DIAS'},
 {'data': '08/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'MELVIN JONNES',
  'reserva': 'CAROLINA DANDARA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EURIDES CUNHA',
  'reserva': 'EDER ROMERO',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '08/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '08/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '08/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '08/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '11/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'SCHERER',
  'reserva': None,
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '11/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'HÉLVIO ESTEVES',
  'reserva': 'CLAUDIMARY REJIANE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '11/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSINÉIA MARTINIANO',
  'motivo': 'AFASTAMENTO 90 DIAS',
  'obs': None},
 {'data': '11/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'VILMA ELIZA',
  'reserva': 'LARISSA NATALINA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CRIMINAL DE LONDRINA',
  'reserva': 'ABIQUEILA PEREIRA DA SILVA',
  'motivo': 'ACOMPANHOU FILHA',
  'obs': None},
 {'data': '11/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '11/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'BEATRIZ DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '11/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'JULIANO STINGHEN',
  'reserva': 'DAIANA CRISTINA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'IGNÊS CORSO',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'RUTH LEMOS',
  'reserva': 'CARINA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'NOEMI MALANGA',
  'reserva': 'LAIS CAVALCANTE',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ CRIMINAL DE LONDRINA',
  'reserva': 'DOMINIQUE MARIA',
  'motivo': 'FÉRIAS',
  'obs': None},
 {'data': '11/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '11/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '11/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'TEREZA CANHADA',
  'reserva': 'JÉSSICA TRINDADE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'EM FRANCISCO PEREIRA',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'CMEI TELMA CAVALIEIRI',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '11/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EM EURIDES CUNHA',
  'reserva': 'EBED ROMERO',
  'motivo': 'DEMISSÃO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS',
  'obs': None},
 {'data': '12/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'NAIR AUZI CORDEIRO',
  'reserva': 'AMANDA DE SOUZA',
  'motivo': 'ACOMPANHAR FILHA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'VILMA ELIZA',
  'reserva': 'LARISSA NATALINA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'SOLANGE ANDRADE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'ROSÂNGELA BIRAL',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'JULIANO STINGHEN',
  'reserva': 'ADRIANA SILVA',
  'motivo': 'ATESTADO',
  'obs': '10 DIAS'},
 {'data': '12/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'IGNÊS CORSO',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO',
  'obs': '4 DIAS'},
 {'data': '12/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'E.M TEREZA CANHADAS',
  'reserva': 'MARCILENE DAS DORES DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'CARLOS DITZ',
  'reserva': 'TAMIRA RIBEIRO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ CRIMINAL DE LONDRINA',
  'reserva': 'DOMINIQUE MARIA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'AMÉRICA SABINO',
  'reserva': 'JANAÍNA DE ASSIS',
  'motivo': 'ATESTADO',
  'obs': '2 DIAS'},
 {'data': '12/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'E.M TEREZA CANHADAS',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'E.M MARIA CANDIDA',
  'reserva': 'Jerri Adriane',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'CMEI TELMA CAVALIEIRI',
  'reserva': None,
  'motivo': 'APOIO / FALTA',
  'obs': None},
 {'data': '12/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'E.M EURIDES CUNHA',
  'reserva': 'EBED ROMERO',
  'motivo': 'DEMISSÃO',
  'obs': None},
 {'data': '12/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '12/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '12/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '12/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '13/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'GASPAR VELLOSO',
  'reserva': 'MARCIA ORTIZ',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'EMILY NATALY',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'JOAQUIM VICENTE CASTRO',
  'reserva': 'FALTANDO SERVENTE',
  'motivo': None,
  'obs': None},
 {'data': '13/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'NATÁLIA MOREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'ROSÂNGELA BIRAL',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'E.M JULIANO STINGHEN',
  'reserva': 'ADRIANA SILVA DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'E.M IGNEZ CORSO',
  'reserva': 'CARINA SUZI',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'E.M TEREZA CANHADAS',
  'reserva': 'VANESSA GONÇALVES',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'E.M EURIDES CUNHA',
  'reserva': 'KEILA MARQUES',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FORUM CRIMINAL',
  'reserva': 'JENIFER FERNANDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'E.M JOAQUIM VICENTE DE CASTRO',
  'reserva': 'FALTA DE SERVENTE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA / POSTO VAGO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'E.M TEREZA CANHADAS',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'E.M MARIA CANDIDO PEIXOTO',
  'reserva': 'Jerri Adriane',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'E.M HAYDEE COLLI',
  'reserva': 'VALDETE APARECIDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '13/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'E.M EURIDES CUNHA',
  'reserva': 'EBED ROMERO',
  'motivo': 'DEMISSÃO',
  'obs': None},
 {'data': '13/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '13/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '13/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '13/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '14/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS',
  'obs': None},
 {'data': '14/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'HELVIO ESTEVES',
  'reserva': 'CLAUDIMARY REJIANE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS',
  'obs': None},
 {'data': '14/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'ATESTADO MÉDICO',
  'reserva': None,
  'motivo': 'ATESTADO MÉDICO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSILEIDE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'JOAQUIM VICENTE CASTRO',
  'reserva': 'FALTANDO SERVENTE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'NATÁLIA MOREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'SOLANGE ANDRADE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'AMÉRICA SABINO',
  'reserva': 'DAYANE DOS SANTOS',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'IGNÊS CORSO',
  'reserva': 'CARINA SUZI',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'MERCEDES MARTINS',
  'reserva': 'MARINA FERNANDES',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'GENI FERREIRA',
  'reserva': 'MONICA JENNIFER',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FORUM CRIMINAL',
  'reserva': 'JENIFER FERNANDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'JULIANO STINGHEN',
  'reserva': 'ADRIANA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE',
  'obs': None},
 {'data': '14/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'E.M TEREZA CANHADAS',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'FRANCISCO PEREIRA JR',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'E.M TELMA CAVALIERI',
  'reserva': 'PATRICIA LIMA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '14/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EURIDES CUNHA',
  'reserva': 'EBED ROMERO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '14/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '14/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '14/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '14/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '15/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'HELVIO ESTEVES',
  'reserva': 'CLAUDIMARY REJIANE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'E.M JOAQUIM VICENTE',
  'reserva': 'FALTANDO SERVENTE',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'NATÁLIA MOREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'SOLANGE ANDRADE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'E.M IGNEZ CORSO',
  'reserva': 'CARINA SUZI',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'E.M NAIR AUZI',
  'reserva': 'AMANDA DE SOUZA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'E.M NOEMIA MALANGA',
  'reserva': 'JULIANA APARECIDA',
  'motivo': 'ATESTADO 2 DIAS',
  'obs': None},
 {'data': '15/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FORUM CRIMINAL DE LONDRINA',
  'reserva': 'JENIFER FERNANDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'E.M JULIANO STINGHEN',
  'reserva': 'ADRIANA DA SILVA DOS SANTOS',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE',
  'obs': None},
 {'data': '15/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'E.M TEREZA CANHADAS',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'E.M MARIA CANDIDO PEIXOTO',
  'reserva': 'JERRY ANDRIANE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '15/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'SANDRA LEME',
  'reserva': 'CINTIA VALIN',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '15/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'PADRE ANCHIETA',
  'reserva': 'DOUGLAS MARTINES',
  'motivo': 'ATESTADO',
  'obs': '5 DIAS'},
 {'data': '15/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '15/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '15/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '15/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'SECRETARIA - PLANETÁRIO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '18/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'E.M. RUTH LEMOS',
  'reserva': 'CARINA SOARES DA SILVA',
  'motivo': 'AT. MÉDICO DE 11 A 24/05',
  'obs': '14 DIAS'},
 {'data': '18/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '18/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '18/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSINÉIA MARTINIANO',
  'motivo': 'POSTO VAGO',
  'obs': '90 DIAS'},
 {'data': '18/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA - ASSIST. SOC.',
  'reserva': 'ANGELINA OLIV. DA SILVA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA',
  'obs': None},
 {'data': '18/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'MARIA LÚCIA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'LUANA BONIFÁCIO',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '18/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'TJ CÍVIL DE LONDRINA',
  'reserva': 'CLÁUDIA B.',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'CARLOS DITZ',
  'reserva': 'ROSELENE BOLETE',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRIANA SILVA DOS SANTOS',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'SECRETARIA DA SAÚDE',
  'reserva': 'VANILDA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'CECÍLIA ERMÍNIA',
  'reserva': 'PAULA CAROLINA',
  'motivo': 'ATESTADO',
  'obs': '7 DIAS'},
 {'data': '18/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'TJ CRIMINAL DE LONDRINA',
  'reserva': 'JENNIFER FERNANDA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNEZ CORSO',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO',
  'obs': '14 DIAS'},
 {'data': '18/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '18/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'IRENE APARECIDA DA SILVA',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'FRANCISCO PEREIRA JÚNIOR',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'SÔNIA PARREIRA',
  'reserva': 'ELCIMARIA BALBINO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '18/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'E.M. PADRE ANCHIETA',
  'reserva': 'DOUGLAS MARTINES',
  'motivo': 'AT. MÉDICO DE 15 A 19/05',
  'obs': '5 DIAS'},
 {'data': '18/05',
  'ausente': 'JEFFERSON',
  'local': 'EM MÁBIO G. PALHANO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '18/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM MÁBIO G. PALHANO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '18/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'EM MARIA TERESA',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '18/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'EM MARIA TERESA',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '19/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'EM VILMA RODR. ROMERO',
  'reserva': 'LUZINÉIA FURQUIM',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'E.M. RUTH LEMOS',
  'reserva': 'CARINA SOARES DA SILVA',
  'motivo': 'AT. MÉD. 11 A 24/05',
  'obs': '14 DIAS'},
 {'data': '19/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '19/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'EM CARLOS DIETZ',
  'reserva': 'RENATA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'FÓRUM DE LONDRINA',
  'reserva': 'CRISTIANE DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'FÓRUM DE LONDRINA',
  'reserva': 'INDIANARA COLTRO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'RODRIGO CEZAR',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRIANA SILVA DOS SANTOS',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'SECRETARIA DE SAÚDE',
  'reserva': 'VANILDA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'CECÍLIA HERMÍNIA',
  'reserva': 'ROSELI REIS DA COSTA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FÓRUM DE LONDRINA',
  'reserva': 'JENIFER FERNANDA',
  'motivo': 'DEMISSÃO',
  'obs': None},
 {'data': '19/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '19/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE',
  'obs': None},
 {'data': '19/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'HIKOMA UDIHARA',
  'reserva': 'LAUANE SILVA',
  'motivo': 'ATESTADO DIAS 18 E 19',
  'obs': None},
 {'data': '19/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'BARTOLOMEU DE GUSMÃO',
  'reserva': 'KELLY DIAS',
  'motivo': 'ATESTADO DIAS 19,20,21,22',
  'obs': None},
 {'data': '19/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'EM SÔNIA PARREIRA DEBEI',
  'reserva': 'ELCIMARIA ALBINO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'E.M. PADRE ANCHIETA',
  'reserva': 'DOUGLAS MARTINES',
  'motivo': 'ATESTADO DIAS 15 A 19',
  'obs': '5 DIAS'},
 {'data': '19/05',
  'ausente': 'JEFFERSON',
  'local': 'EM MÁBIO G. PALHANO',
  'reserva': 'EM. NÍSSIA ROCHA',
  'motivo': None,
  'obs': None},
 {'data': '19/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM MÁBIO G. PALHANO',
  'reserva': 'EM. NÍSSIA ROCHA',
  'motivo': None,
  'obs': None},
 {'data': '19/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'CRAS SUL E EM',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '19/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'CRAS SUL E EM',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '20/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'ATESTADO MÉDICO 1 DIA',
  'reserva': None,
  'motivo': 'ATESTADO MÉDICO 1 DIA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'EM RUTH LEMOS',
  'reserva': 'CARINA SOARES DA SILVA',
  'motivo': 'AT. MÉD. 11 A 24/05',
  'obs': '14 DIAS'},
 {'data': '20/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'ALINE CRISTINA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '20/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA ASSIST. SOCIAL',
  'reserva': 'ANGELINA OLIVEIRA SILVA',
  'motivo': 'ATESTADO 18, 19 E 20.',
  'obs': None},
 {'data': '20/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '20/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'MARIA EDUARDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '20/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'EM VANDERLAINE',
  'reserva': 'ROSÂNGELA AP. DA SILVA',
  'motivo': 'DECLARAÇÃO ACOMP.',
  'obs': None},
 {'data': '20/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'RODRIGO CEZAR',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRIANA DA SILVA',
  'motivo': 'ATESTADO 10 DIAS',
  'obs': None},
 {'data': '20/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'SECRETARIA MUN. SAÚDE',
  'reserva': 'VANILDA APARECIDA',
  'motivo': 'ATESTADO DE 7 DIAS',
  'obs': None},
 {'data': '20/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'EM CORVETA CAMAQUÃ',
  'reserva': 'GLÁUCIA REGINA',
  'motivo': 'ATESTADO DE 2 DIAS',
  'obs': None},
 {'data': '20/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '20/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'JENNIFER FERNANDA',
  'motivo': 'DEMISSÃO',
  'obs': 'CONTRATAR'},
 {'data': '20/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '20/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '20/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'EM IRENE AP. DA SILVA',
  'reserva': None,
  'motivo': 'APOIO / ENTROU 8H',
  'obs': None},
 {'data': '20/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'EM BARTOLOMEU DE GUSM.',
  'reserva': 'KELLY DIAS',
  'motivo': 'ASSUNTOS PESSOAIS',
  'obs': '19,20,21,22'},
 {'data': '20/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'EM GENI FERREIRA',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '20/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'LAUANA SILVA',
  'motivo': 'CONSULTA MÉDICA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'JEFFERSON',
  'local': 'EM NÍSSIA ROCHA',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM NÍSSIA ROCHA',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '20/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA DE CULTURA',
  'reserva': 'REGINA APARECIDA DA SILVA',
  'motivo': 'PAGAR INSALUBRIDADE.',
  'obs': None},
 {'data': '20/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'CMEI VALÉRIA VERONESI',
  'reserva': 'COBRINDO MARIA AUGUSTA',
  'motivo': 'TRANSFERIDA',
  'obs': None},
 {'data': '21/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'EM VILMA RODR. ROMERO',
  'reserva': 'LUZINÉIA FURQUIM',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'EM RUTH LEMOS',
  'reserva': 'CARINA SOARES DA SILVA',
  'motivo': 'AT. MÉD. 11 A 24/05',
  'obs': '14 DIAS'},
 {'data': '21/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '21/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'EM EUGÊNIO BRUGIN',
  'reserva': 'MARIA CASTORINO RIBEIRO',
  'motivo': 'ATESATADO 20,21,22',
  'obs': None},
 {'data': '21/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '21/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA DE CULTURA',
  'reserva': 'REGINA AP. DA SILVA',
  'motivo': 'PAGAR INSALUBRIDADE.',
  'obs': None},
 {'data': '21/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'CRISTIANE DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '21/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM CARLOS C. BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'ATESTADO DE 180 DIAS',
  'obs': 'CONTRATAR'},
 {'data': '21/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'SECRETARIA ASSIST. SOCIAL',
  'reserva': 'CÍNTIA GONZAGA',
  'motivo': 'ATESTADO 18,19,20,21',
  'obs': None},
 {'data': '21/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'EM MAESTRE DE HELD',
  'reserva': 'OLGA ANGÉLICA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM AMÉRICA SABINO',
  'reserva': 'DAYANE DOS SANTOS MACEDO',
  'motivo': 'ATESTADO 20,21',
  'obs': None},
 {'data': '21/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'SECRETARIA DE SAÚDE',
  'reserva': 'VANILDA APARECIDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '21/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'EM CORVETA CAMAQUÃ',
  'reserva': 'GLÁUCIA REGINA',
  'motivo': 'ATESTADO DE 2 DIAS',
  'obs': None},
 {'data': '21/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'JENIFER FERNANDA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '21/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '21/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'IRENE APARECIDA',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'EM BARTOLOMEU GUSMÃO',
  'reserva': 'KELLY DIAS',
  'motivo': 'ASSUNTOS PESSOAIS',
  'obs': None},
 {'data': '21/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'EM LAURA VIRGÍNIA',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '21/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'LUANA SILVA',
  'motivo': 'ATESTADO 20,21,22',
  'obs': None},
 {'data': '21/05',
  'ausente': 'JEFFERSON',
  'local': 'EM NÍSSIA ROCHA',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '21/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM NÍSSIA ROCHA',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '21/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'SECRETARIA DE CULTURA',
  'reserva': 'REGINA APARECIDA DA SILVA',
  'motivo': 'PAGAR INSALUBRIDADE.',
  'obs': None},
 {'data': '21/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'CMEI VALÉRIA VERONESI',
  'reserva': 'COBRINDO MARIA AUGUSTA',
  'motivo': 'TRANSFERIDA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '22/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'CMEI VALÉRIA VERONESI',
  'reserva': 'MARIA AUGUSTA MECCHI',
  'motivo': 'TRANSFERIDA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'SELMA DE JESUS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '22/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA ASSIST. SOCIAL',
  'reserva': 'CÍNTIA GONZAGA CARVALHO',
  'motivo': 'ATESTADO 18,19,20,21,22',
  'obs': None},
 {'data': '22/05',
  'ausente': 'ANDRÉ GUSTAVO SENA',
  'local': 'EM VILMA RODRIGUES ROMERO',
  'reserva': 'LUZINÉIA FURQUIM',
  'motivo': 'POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '22/05',
  'ausente': 'JACQUELINE AP. DE PAULA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'CRISTIANE DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM CARLOS C. BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': 'CONTRATAR ?'},
 {'data': '22/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '22/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'ROSANGELA BIRAL',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'CMEI NÍSSIA ROCHA',
  'reserva': 'VALQUÍRIA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM AMÉRCIA SABINO',
  'reserva': 'JANAÍNA DE ASSIS PEREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'CMEI HELLENA OMETO',
  'reserva': 'ESTEFANI MORAIS',
  'motivo': 'ATESTADO 21,22',
  'obs': None},
 {'data': '22/05',
  'ausente': 'PAULA CAROLINA FERNANDES DE MOURA',
  'local': 'EM CECÍLIA HERMÍNIA',
  'reserva': 'ROSELI REIS DA COSTA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'JENIFER FERNANDA',
  'motivo': 'DEMISSÃO',
  'obs': 'CONTRATAR'},
 {'data': '22/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '22/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '22/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'EM JOSÉ GASPARINI - ANEXO',
  'reserva': 'RENATA FERREIRA',
  'motivo': 'LEVOU FILHA AO MÉDICO',
  'obs': None},
 {'data': '22/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'EM BARTOLOMEU GUSMÃO',
  'reserva': 'KELLY DIAS',
  'motivo': 'ASSUNTOS PESSOAIS',
  'obs': None},
 {'data': '22/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'E.M MARIA CANDIDO PEIXOTO',
  'reserva': 'JERRY ANDRIANE',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '22/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'LAUANE SILVA',
  'motivo': 'ATESTADO 20, 21 E 22.',
  'obs': None},
 {'data': '22/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '22/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '22/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '22/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '25/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '25/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'FALTOU',
  'reserva': None,
  'motivo': 'FALTOU',
  'obs': None},
 {'data': '25/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'CMEI VALÉRIA VERONESI',
  'reserva': 'MARIA AUGUSTA MECCHI',
  'motivo': 'TRANSFERIDA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '25/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'ABIQUEILA PEREIRA DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSILEIDE DE CASTRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '25/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'SECRETARIA ASSIST. SOCIAL',
  'reserva': 'CYNTIA GONZAGA CARVALHO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA',
  'obs': 'CONTRATADA'},
 {'data': '25/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'ATESTADO',
  'reserva': None,
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '25/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'MARIA EDUARDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'EM CECÍLIA ERMÍNIA',
  'reserva': 'ROSELI REIS DA COSTA',
  'motivo': 'PERÍODO DA TARDE',
  'obs': None},
 {'data': '25/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM AMÉRICA SABINO',
  'reserva': 'JANAÍNA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'EM LUIS MARQUES CASTELO',
  'reserva': 'LUCILENE DE SOUZA VIEIRA',
  'motivo': 'ATESTADO ÓBITO DO PAI',
  'obs': None},
 {'data': '25/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'EM GENI FERREIRA',
  'reserva': 'MONNICA JHENNIFER',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '25/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FALTOU',
  'reserva': None,
  'motivo': 'FALTOU',
  'obs': None},
 {'data': '26/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '25/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTOU',
  'reserva': None,
  'motivo': 'FALTOU',
  'obs': None},
 {'data': '26/05',
  'ausente': 'EDUCIANDRA',
  'local': 'EM SAN IZIDRO',
  'reserva': 'CLAUDINÉIA M. DOS SANTOS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '25/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRIANA DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'ZILDA POTIL MAGALHÃES',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '25/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'E.M IRENE APARECIDA',
  'reserva': None,
  'motivo': 'APOIO',
  'obs': None},
 {'data': '25/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'EM JOSÉ GASPARINI',
  'reserva': 'RENATA FERREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'EM TELMA CAVALHERI',
  'reserva': 'PATRÍCIA DE LIMA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '25/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'LAUANE ISABELE DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'JEFFERSON',
  'local': 'EM MARI CARRERA',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '25/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM MARI CARRERA',
  'reserva': None,
  'motivo': 'LIMPEZA PESADA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRIANA DA SILVA',
  'motivo': 'PAGAR INSALUBRIDADE',
  'obs': None},
 {'data': '25/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'ZILDA POTIL MAGALHÃES',
  'motivo': 'PERÍODO DA TARDE',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '26/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'CMEI VALÉRIA VERONESI',
  'reserva': 'MARIA AUGUSTA MECCHI',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '26/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'ALINE CRISTINA RIBEIRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': 'CONTRATADA'},
 {'data': '26/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'LARISSA FARIAS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'MARIA EDUARDA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'EM SÔNIA PARREIRA',
  'reserva': 'SIMONE JANUÁRIO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRIANA DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'SECRETARIA ASSIST. SOCIAL',
  'reserva': 'CYNTIA GONZAGA CARVALHO',
  'motivo': 'ATESTADO DE 02 DIAS',
  'obs': None},
 {'data': '26/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'EM GENI FERREIRA',
  'reserva': 'MÔNICA JENNIFER',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'FRANCIELE',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '26/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'EDUCIANDRA',
  'local': 'EM HAYDEE COLLI MONTEIRO',
  'reserva': 'GILCINÉIA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE',
  'obs': None},
 {'data': '26/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'EM JOSÉ GASPARINI',
  'reserva': 'FAUSTO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'EM JOSÉ GASPARINI - ANEXO',
  'reserva': 'RENATA FERREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '26/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'EM TELMA CAVALHERI',
  'reserva': 'PATRÍCIA DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'ATESTADO',
  'reserva': None,
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '26/05',
  'ausente': 'JEFFERSON',
  'local': 'EM CARLOS COSTA BRANCO',
  'reserva': 'TOLDOS',
  'motivo': 'APONTAMENTO IMR ABRIL',
  'obs': None},
 {'data': '26/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM CARLOS COSTA BRANCO',
  'reserva': 'TOLDOS',
  'motivo': 'APONTAMENTO IMR ABRIL',
  'obs': None},
 {'data': '26/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'CRAS SUL - B',
  'reserva': 'TERMINAR TRABALHO',
  'motivo': None,
  'obs': None},
 {'data': '26/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'EM CORVET CAMAQUÃ',
  'reserva': 'TIRAR LIMO DO CHÃO',
  'motivo': 'URGÊNCIA IMR DE JUNHO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '27/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'EM. MALVINA POPI',
  'reserva': 'LAÍS BATISTA FERREIRA',
  'motivo': 'ATESTADO 1 DIA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'CMEI VALÉRIA VERONESI',
  'reserva': 'MARIA AUGUSTA MECCHI',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '27/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'EM. VILMA RODRIGUES',
  'reserva': 'LUZINÉIA FURQUIM',
  'motivo': 'POSTO VAGO',
  'obs': 'COBRIU A TARDE'},
 {'data': '27/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'CMEI DURVALINA P. ASSIS',
  'reserva': 'ELAINE FERMINO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'HELLEN S. DOS SANTOS DA SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': 'CONTRATADA'},
 {'data': '27/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'ATESTADO',
  'reserva': None,
  'motivo': 'ATESTADO',
  'obs': 'ATESTADO 27,28'},
 {'data': '27/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'FÓRUM CÍVIL',
  'reserva': 'MARIA EDUARDA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'EM CARLOS DIETZ',
  'reserva': 'RENATA GARCIA',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRINA DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'EM MARINA SABÓIA',
  'reserva': 'JULIANA DA SILVA DIAS',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'EM GENI FERREIRA',
  'reserva': 'MÔNICA JENNIFER',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '27/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'EDUCIANDRA',
  'local': 'EM HAYDEE COLLI',
  'reserva': 'GILCINÉIA LILIANE',
  'motivo': 'ATESTADO 26 E 27',
  'obs': None},
 {'data': '27/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE',
  'obs': None},
 {'data': '27/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'EM JOSÉ GASPARINI - ANEXO',
  'reserva': 'RENATA FERREIRA',
  'motivo': 'ATESTADO 10 DIAS',
  'obs': None},
 {'data': '27/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'CMEI IOLANDA SALGADO',
  'reserva': 'MOACIR MONSATO',
  'motivo': 'ATESTADO 4 DIAS',
  'obs': None},
 {'data': '27/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'EM TELMA CAVALHERI',
  'reserva': 'PATRÍCIA DE LIMA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '27/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EM MARIA TERESA',
  'reserva': 'VILMA BRAGA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '27/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '27/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '27/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'RUTH LEMOS / MARISA ARRUDA',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '27/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'RUTH LEMOS / MARISA ARRUDA',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '28/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'ROSEMEIRE PEREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'CMEI VALERIA VERONESI',
  'reserva': 'MARIA AUGUSTA MECCHI',
  'motivo': 'TRANSFERIDA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'EM VILMA RODRIGUES',
  'reserva': 'LUZINEIA FURQUIM',
  'motivo': 'POSTO VAGO',
  'obs': 'SEM INSALUBRIDADE'},
 {'data': '28/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'EM MARIA SHIRLEY B. LIRA',
  'reserva': 'VANILCE CÍCERA',
  'motivo': 'COMPENSAR HR EXTRA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'HELLEN SAMARA DOS SANTOS SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'ATESTADO',
  'reserva': None,
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM. CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'MARIA EDUARDA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'E.M MERCEDES MARTINS',
  'reserva': 'MARIA FERNANDES',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'EM AMÉRICA SABINO',
  'reserva': 'DAIANE DOS SANTOS',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'EM MARINA SABÓIA',
  'reserva': 'LUCIANA LOURENÇA RIBEIRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'EM GENI FERREIRA',
  'reserva': 'MONICA JENNIFER',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'EM IGNÊS CORSO ANDREAZZA',
  'reserva': 'FRANCIELE',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '28/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE',
  'obs': None},
 {'data': '28/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'EM JOSÉ GASPARINI - ANEXO',
  'reserva': 'RENATA FERREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '28/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'CMEI YOLANDA SALGADO',
  'reserva': 'MOACIR MOSATO',
  'motivo': 'ATESTADO 4 DIAS',
  'obs': None},
 {'data': '28/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'EM TELMA CAVALHERI',
  'reserva': 'PATRÍCIA DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '28/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'EM AMÉRICA SABINO',
  'reserva': 'WESLEY GONÇALVES',
  'motivo': 'ATESTADO 7 DIAS',
  'obs': None},
 {'data': '28/05',
  'ausente': 'JEFFERSON',
  'local': 'EM MÁBIO G. PALHANO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '28/05',
  'ausente': 'JÚNIOR ALVES',
  'local': 'EM MÁBIO G. PALHANO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '28/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'EM MARIA CANDIDO',
  'reserva': 'JENIFER SOUZA',
  'motivo': None,
  'obs': None},
 {'data': '28/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'EM HIKOMA UDIHARA',
  'reserva': 'ZILDA MAGALHÃES',
  'motivo': None,
  'obs': None},
 {'data': '29/05',
  'ausente': 'ALESSANDRA DA SILVA CRUZ',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS / POSTO VAGO',
  'obs': 'CONTRATAR'},
 {'data': '29/05',
  'ausente': 'ANDRÉ GUSTAVO SENNA',
  'local': 'EM JULIANO STINGHEN',
  'reserva': 'ADRIANA DA SILVA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'ÂNGELA MARIA LOPES',
  'local': 'EM MARINA SABÓIA',
  'reserva': 'LUCIANA LOURENÇO RIBEIRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'ANNA RITA DA SILVA',
  'local': 'INSS',
  'reserva': None,
  'motivo': 'INSS',
  'obs': 'CONTRATAR'},
 {'data': '29/05',
  'ausente': 'DAIANE APARECIDA R. DA SILVA',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'ELAINE R. MALACHINI HENRIQUES',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'ROSELEIDE CASTRO',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'FLÁVIA PERES KERCHE DE MENEZES',
  'local': 'EM MARIA SHIRLEY B. LIRA',
  'reserva': 'VANÍLCE CÍCERA',
  'motivo': 'COMPENSAR HORAS EXTRAS',
  'obs': None},
 {'data': '29/05',
  'ausente': 'HELLEN SAMARA DOS SANTOS SILVA',
  'local': 'RESCISÃO DIRETA',
  'reserva': None,
  'motivo': 'RESCISÃO DIRETA / POSTO VAGO',
  'obs': 'CONTRATADA'},
 {'data': '29/05',
  'ausente': 'JACQUELINE APARECIDA DE PAULA',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'SILVIA REGINA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'LAÍS MIRANDA DA SILVEIRA',
  'local': 'EM CARLOS COSTA BRANCO',
  'reserva': 'ELIZETE DE OLIVEIRA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '29/05',
  'ausente': 'LUCI FERNANDES DE SÁ ESTÉRCIO',
  'local': 'FÓRUM CRIMINAL',
  'reserva': 'MARIA EDUARDA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '29/05',
  'ausente': 'LUCIENE VIEIRA BOLETTI',
  'local': 'EM MERCEDES MARTINS',
  'reserva': 'MARINA FERNANDA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'MARIA DE FÁTIMA S. P. DA SILVA',
  'local': 'E.M AMERICA SABINO',
  'reserva': 'DANIELLE PRUDENCIO',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '29/05',
  'ausente': 'MARÍLIA DE OLIVEIRA BISPO',
  'local': 'PREFEITURA DE LONDRINA',
  'reserva': 'VALDINEIA REGINA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'PAULA C. FERNANDES DE MOURA',
  'local': 'EM GENI FERREIRA',
  'reserva': 'MONICA JENNIFER',
  'motivo': 'ATESTADO',
  'obs': None},
 {'data': '29/05',
  'ausente': 'PRISCILA SILVA DE MENEZES',
  'local': 'EM ZUMBI DOS PALMARES',
  'reserva': 'GERALDO SEVERINO DA SILVA',
  'motivo': 'INTERNADO',
  'obs': None},
 {'data': '29/05',
  'ausente': 'SAMONITA DA SILVA SANTOS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'SILVANA CRISTINA DOS SANTOS',
  'local': 'IGNÊS CORSO ANDREAZZA',
  'reserva': 'CARINA SUZI FIDELIS',
  'motivo': 'ATESTADO DE 14 DIAS',
  'obs': None},
 {'data': '29/05',
  'ausente': 'STHEFANE MAYARA MARTINS',
  'local': 'FALTA',
  'reserva': None,
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'BRUNA DANIELLY DA SILVA SANTOS',
  'local': 'LICENÇA MATERNIDADE',
  'reserva': None,
  'motivo': 'LICENÇA MATERNIDADE / POSTO VAGO',
  'obs': None},
 {'data': '29/05',
  'ausente': 'ELISÂNGELA APARECIDA DA SILVA',
  'local': 'E.M GASPARINI',
  'reserva': 'RENATA FERREIRA',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'FÁTIMA APARECIDA',
  'local': 'CMEI YOLANDA SALGADO',
  'reserva': 'MOACIR MOSATO',
  'motivo': 'ATESTADO 4 DIAS',
  'obs': None},
 {'data': '29/05',
  'ausente': 'LUZIA DE OLIVEIRA',
  'local': 'E.M TELMA CAVALIERI',
  'reserva': 'PATRICIA DE LIMA',
  'motivo': 'POSTO VAGO',
  'obs': None},
 {'data': '29/05',
  'ausente': 'PAULO AQUINO DE ALMEIDA JÚNIOR',
  'local': 'E.M AMERICA SABINO',
  'reserva': 'WESLEY GONÇALVES',
  'motivo': 'FALTA',
  'obs': None},
 {'data': '29/05',
  'ausente': 'JEFFERSON',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '29/05',
  'ausente': 'JÚNIOR ALVES',
  'local': None,
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '29/05',
  'ausente': 'CARLOS HENRIQUE SANTOS OLIVEIRA',
  'local': 'MARIA TERESA MELEIRO',
  'reserva': None,
  'motivo': None,
  'obs': None},
 {'data': '29/05',
  'ausente': 'LINCOLN GUSTAVO MENDES',
  'local': 'MARCENARIA PML',
  'reserva': None,
  'motivo': None,
  'obs': None}]
